name: Release
on:
  workflow_dispatch:
    inputs:
      ReleaseHeader:
        description: The header to be added to the release.
        required: false
jobs:
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.14
      - name: Github Repository Metadata
        id: metadata
        uses: varunsridharan/action-repository-meta@2.2
      - name: Update Changelog for Release
        id: changelog
        uses: natescherer/changelog-management-action@main
        with:
          mode: release
          releaseVersion: ${{ steps.gitversion.outputs.SemVer }}
      - name: Update README Description
        uses: natescherer/reactive-readme@main
        with:
          value: ${{ steps.metadata.outputs.description }}
          section: description
      - name: Update README Inputs/Outputs
        uses: natescherer/update-action-readme@feature/handle-no-outputs
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{ github.workspace }}
      # - name: Commit Changes to Repo
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Release v${{ steps.gitversion.outputs.SemVer }}
      #     file_pattern: ":!test\\* :!test/*"
      # - name: Create Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: v${{ steps.gitversion.outputs.MajorMinorPatch }}
      #     body: |
      #       # Release v${{ steps.gitversion.outputs.SemVer }}
      #       ${{ github.event.inputs.ReleaseHeader}}

      #       ## Changes
      #       ${{ steps.changelog.outputs.releasenotes }}