name: Release
on: workflow_dispatch
jobs:
  Test:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Update Changelog for Release
        id: changelog
        uses: natescherer/changelog-management-action@main
        with:
          mode: release
          releaseversion: ${{ steps.gitversion.outputs.NuGetVersionV2 }}
      - name: Get Metadata
        uses: juliojimenez/yamler@v0
        id: metadata
        with:
          yaml-file: metadata.yml
      - name: Check if Repository Description Matches Metadata
        run: |
          $Description = "${{ steps.metadata.outputs.description }}"
          $RepoSplat = @{
            Uri = "https://api.github.com/repos/$env:GITHUB_REPOSITORY"
            Method = "GET"
            Headers = @{
              Accept = "application/vnd.github.v3+json"
            }
          }
          $RepoData = Invoke-RestMethod @RepoSplat

          if ($RepoData.Description -ne $Description) {
            throw "Repo description does not match metadata! Please fix and re-run."
          }
      - name: Update README
        run: |
          $Description = "${{ steps.metadata.outputs.description }}"
          [string]$Content = Get-Content -Path "$env:GITHUB_WORKSPACE\README.md" -Raw
          $Content = $Content -replace "<!-- REPLACER START: desc -->.*<!-- REPLACER END: desc -->","<!-- REPLACER START: desc -->$Description<!-- REPLACER END: desc -->"
          Out-File -InputObject $Content -FilePath "$env:GITHUB_WORKSPACE\README.md"  -NoNewline